In [1]:
import pandas as pd
import json

In [2]:
csv_path = r"C:\Users\chava\OneDrive\Desktop\UAM\Intel. de Negocios\3. Corte\Youtube\archive (1)\Youtube_data\Countries_data\USvideos.csv"

In [14]:
df_videos = pd.read_csv(csv_path, delimiter=';')

C:\Users\chava\AppData\Local\Temp\ipykernel_34272\4038046405.py:1: DtypeWarning: Columns (16,17,18,19,20,21,22,23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df_videos = pd.read_csv(csv_path, delimiter=';')

In [15]:
df_videos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_videos = df_videos.loc[:, ~df_videos.columns.str.contains('^Unnamed')]

In [17]:
df_videos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

In [18]:
df_videos.isnull().sum()

video_id                   515
trending_date             6326
title                     6488
channel_title             6690
category_id               6943
publish_time              7114
tags                      7669
views                     7737
likes                     7755
dislikes                  7763
comment_count             7763
thumbnail_link            7763
comments_disabled         7776
ratings_disabled          7838
video_error_or_removed    7838
description               8408
dtype: int64

In [19]:
df_videos = df_videos.dropna()

In [20]:
df_videos = df_videos.dropna(how='all')

In [21]:
df_videos = df_videos.fillna(0)

In [22]:
df_videos.isnull().sum()

video_id                  0
trending_date             0
title                     0
channel_title             0
category_id               0
publish_time              0
tags                      0
views                     0
likes                     0
dislikes                  0
comment_count             0
thumbnail_link            0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
description               0
dtype: int64

In [23]:
json_path = r"C:\Users\chava\OneDrive\Desktop\UAM\Intel. de Negocios\3. Corte\Youtube\archive (1)\Youtube_data\Countries_data\US_category_id.json"

In [24]:
with open(json_path, 'r') as f:
    category_data = json.load(f)

In [25]:
categories = pd.json_normalize(category_data['items'], sep='_')

In [26]:
print("Datos iniciales del JSON:")
print(categories.head())

Datos iniciales del JSON:
                    kind                                               etag  \
0  youtube#videoCategory  "m2yskBQFythfE4irbTIeOgYYfBU/Xy1mB4_yLrHy_BmKm...
1  youtube#videoCategory  "m2yskBQFythfE4irbTIeOgYYfBU/UZ1oLIIz2dxIhO45Z...
2  youtube#videoCategory  "m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...
3  youtube#videoCategory  "m2yskBQFythfE4irbTIeOgYYfBU/HwXKamM1Q20q9BN-o...
4  youtube#videoCategory  "m2yskBQFythfE4irbTIeOgYYfBU/9GQMSRjrZdHeb1OEM...

   id         snippet_channelId     snippet_title  snippet_assignable
0   1  UCBR8-60-B28hp2BmDPdntcQ  Film & Animation                True
1   2  UCBR8-60-B28hp2BmDPdntcQ  Autos & Vehicles                True
2  10  UCBR8-60-B28hp2BmDPdntcQ             Music                True
3  15  UCBR8-60-B28hp2BmDPdntcQ    Pets & Animals                True
4  17  UCBR8-60-B28hp2BmDPdntcQ            Sports                True

In [27]:
print("\nValores nulos en cada columna antes de limpiar:")
print(categories.isnull().sum())

Valores nulos en cada columna antes de limpiar:
kind                  0
etag                  0
id                    0
snippet_channelId     0
snippet_title         0
snippet_assignable    0
dtype: int64

In [28]:
categories = categories.drop(columns=['kind', 'etag'])

In [29]:
print("\nDatos después de eliminar columnas innecesarias:")
print(categories.head())

Datos después de eliminar columnas innecesarias:
   id         snippet_channelId     snippet_title  snippet_assignable
0   1  UCBR8-60-B28hp2BmDPdntcQ  Film & Animation                True
1   2  UCBR8-60-B28hp2BmDPdntcQ  Autos & Vehicles                True
2  10  UCBR8-60-B28hp2BmDPdntcQ             Music                True
3  15  UCBR8-60-B28hp2BmDPdntcQ    Pets & Animals                True
4  17  UCBR8-60-B28hp2BmDPdntcQ            Sports                True

In [30]:
df_videos.to_csv(r"C:\Users\chava\OneDrive\Desktop\UAM\Intel. de Negocios\3. Corte\Youtube\archive (1)\Youtube_data\Countries_data\USvideos_cleaned.csv", index=False, sep=';')

In [31]:
categories.to_json(r"C:\Users\chava\OneDrive\Desktop\UAM\Intel. de Negocios\3. Corte\Youtube\archive (1)\Youtube_data\Countries_data\US_category_id_cleaned.json", orient='records', lines=True)